FROM golang:1.24-bullseye as builder

WORKDIR /app
COPY . .

RUN go build -o migrate ./cmd/migrate

FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/migrate ./migrate
COPY cmd/migrate/migrations ./migrations

CMD ["./migrate"]
